### PR TITLE
Documentation improvements

### PR DESCRIPTION
**Pull request by lmagyar**
## Proposed Changes

Typos, consistent formatting, consistent wording, alphabetical order after the mega-merge in v0.12.0.

~One functional improvement: Protect local subnets only if non-userspace networking is used ***and accepting routes are enabled***.~

### CODE REVIEW

**Comment by lmagyar** [comment]
Rebased, to prevent merge conflicts (proxy service code will change a lot).

**Comment by lmagyar** [comment]
Moved the only functional change into separate PR. This is only docs and log messages change.

**Comment by frenck** [comment]
@lmagyar Can you rebase this PR? I think it would be nice to include in the next cut

**Comment by lmagyar** [comment]
Rebased - with some manual conflict resolution, git gone wild.

**Review by frenck — APPROVED** [review]
Thanks, @lmagyar 👍 

../Frenck

**Pull request merged**
