### PR TITLE
Update Tailscale Version

### PR DESCRIPTION
**Pull request by Maeur1**
# Proposed Changes

Updating the version of the tailscale package

## Summary by CodeRabbit

- **Chores**
  - Updated Tailscale to version 1.68.0 from 1.66.4 for improved performance and stability.

### CODE REVIEW

**Comment by Maeur1** [comment]
Heya just wanting to assist by making a PR to update the tailscale package? I am assuming this is how this is done but happy to update the PR to fix up anything/test out the addon before pushing it out

**Comment by lmagyar** [comment]
Note (form another user): the repo is already on v1.68.2, just not released yet.

**Comment by tjorim** [comment]
A bot automatically opens PRs to update this: https://github.com/hassio-addons/addon-tailscale/pull/385

**Comment by Maeur1** [comment]
Ahhh  I just hadn't seen that, good to know it updates it automatically! Time to close this thanks

**Pull request closed without merging**
