### PR TITLE
Allow Linux optimizations (UDP GRO for forwarding) on multiple default interfaces and IPv6

### PR DESCRIPTION
**Pull request by lmagyar**
# Proposed Changes

SSIA

## Related Issues

PR #351 #360

## Summary by CodeRabbit

- **New Features**
  - Enhanced network interface handling to support UDP GRO forwarding, improving network performance.

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @lmagyar 👍 

../Frenck

**Comment by lmagyar** [comment]
And now I'm thinking why Tailscale suggested only the default interface?

That is good for exit nodes, but what about advertised subnets?

Shouldn't we do this optimization for the advertised subnets' interfaces also, like the MSS clamping?

**Comment by frenck** [comment]
I cannot answer that suggestion. If they explicitly suggest it as such, there must be some kind of reason for it on their end.

**Comment by lmagyar** [comment]
FYI: Certainly you are right, they check for the default interface only, for whatever reason. https://github.com/tailscale/tailscale/blob/main/ipn/ipnlocal/local.go#L5523

**Pull request merged**
