### PR TITLE
Remove duplicate status checks from dependent S6 services

### PR DESCRIPTION
**Pull request by lmagyar**
# Proposed Changes

Minor code quality improvement.

The `proxy` and `taildrop` services are waiting for `post-tailscaled`, so move the status checks from the beginning of `proxy` and `taildrop` to the end of `post-tailscaled`.

### CODE REVIEW

**Comment by seagyn** [comment]
@lmagyar Are you able to add labels to this? I see it's the only action that fails. I'd like to see funnel getting implemented.

**Comment by frenck** [comment]
> @lmagyar Are you able to add labels to this? I see it's the only action that fails. I'd like to see funnel getting implemented.

No, that is not how GitHub work, nor is that a concern or limiting factor at this point.

../Frenck

**Comment by seagyn** [comment]
Sorry, I was referring to this: 

image

image

With the hope that if all the checks were passing, then it should pass before pinging you to ask what is preventing something like this from going in? I'm mainly interested in #197

**Comment by frenck** [comment]
I know what you are referring too... but your comment makes no sense, and only shows you have no clue on how GitHub even works...

We all have interest in many things. Pinging won't help either. If anything, a ping makes me skip things on purpose, as I don't want / will lure myself into a system of "handling the loudest".


Just be patient please. 🙏 

../Frenck

**Comment by seagyn** [comment]
I'm sorry Frank, I'm not sure why their is aggression here after a simple question not even directed at you. I know very well how GitHub works, thanks.

I won't hold my breath especially after a threat like that. Literally no one was putting pressure but purely stating a desire.

Cheers.

**Comment by frenck** [comment]
A threat / aggression? Are you ok? :)


Don't take it so heavy. I am just explaining that you comment on labels didn't make sense, as a PR contributor/author can't set them, thus you might not be aware how GitHub works.

Additionally you mentioned about pinging, but that is something that can be demanding, even when not meant that way. 🤷‍♂️ 


There is no aggression or mad face from my end at all here 😕 


../Frenck

**Comment by seagyn** [comment]
I'm ok, thanks.

You first response is an overarching statement that I have no idea how GitHub works when a "PR contributors cannot add labels and this isn't the blocker for this. I'll give feedback in due course." Is much less aggressive.

Anyway, thanks for all your open source projects and contributions. There was no intention to put pressure on you at all but rather to see if I could help this along in anyway.

Cheers.

**Comment by lmagyar** [comment]
not stale

**Comment by lmagyar** [comment]
not stale

**Comment by lmagyar** [comment]
not stale

**Review by frenck — APPROVED** [review]
Thanks, @lmagyar 👍 

../Frenck

**Pull request merged**
