### PR TITLE
bump Tailscale version: 1.34.1

### PR DESCRIPTION
**Pull request by networkpanic**
# Proposed Changes

bump Tailscale to 1.34.1
bump nginx to 1.22.1-r0

The nginx bump was needed as pinned in the Dockerfile is not found on the repos anymore [Failed Build](https://github.com/hassio-addons/addon-tailscale/actions/runs/3715885676/jobs/6301583363)

Fixes: https://github.com/hassio-addons/addon-tailscale/issues/124

### CODE REVIEW

**Comment by leoherzog** [comment]
Hey @frenck, any reason this can't be merged? I'm excited to use Tailscale Funnels with Home Assistant.

**Comment by alexjacostal** [comment]
@iancleary @frenck I think this is only waiting for a label to be merged, I understand that there are more important things to do, but this add on is getting pretty stale please give a little of love we all be pretty grateful, thanks for the good work.

**Comment by networkpanic** [comment]
@alexjacostal unfortunately i don't have permissions to add labels to the PR.

**Comment by iancleary** [comment]
> @alexjacostal unfortunately i don't have the permission to add labels.
> 
> 

Same, it's waiting for review by a team member (I don't have permission either). 

I know we all appreciate the work on the add on and the pending review 😊

**Comment by lmagyar** [comment]
Until it is merged I forked the repo and updated it to Tailscale v1.34.2, and bumped the add-on base image also to v13.0.1.

And I merged and fixed the TLS cert fetching PR #89 also.

See: https://github.com/lmagyar/homeassistant-addon-tailscale

I will create some new PR-s soon.

**Comment by lmagyar** [comment]
FYI
My PR #133 bumps TS to 1.34.2 and also bumps the base image, repairs some minor bugs, etc.
So PR #127 I think can be closed.

**Comment by networkpanic** [comment]
Thank you @lmagyar 
Hope your PR's don't get ignored aswell

**Pull request closed without merging**
