### PR TITLE
Remove stale bot

### PR DESCRIPTION
**Pull request by ShadowJonathan**
...as it has been firing continuously on various issues and PRs since [the last commit](https://github.com/hassio-addons/addon-tailscale/commit/6be6bff0fb894fd9f8adc441663c086c0ba4f4b6), while the maintainer hasn't responded to any of them.

# Proposed Changes

For the main home assistant repo, adding a stale bot to reduce/reap issues on problems that have "likely" been fixed in a recent release is understandable, however, in this repo, where there are multiple issues that are tracked consistently between PRs and other issues, a stale bot just risks each legitimate issue from being closed pre-emptively.

What's worse, is that there has been no maintainer activity since **September 2022**, about 4 months, where the stale bot poised to reap many issues that the maintainer promised to address, but has not on the meantime.

An alternative solution to this would be for the maintainer to add the `no-stale` label to all of the mentioned issues, or the issues that they care about explicitly / have shown interest in. The label that does this is defined [here](https://github.com/hassio-addons/workflows/blob/a853f1f5e325b637942d084723e21457e92b1d01/.github/workflows/stale.yaml#L24).

## Related Issues

- https://github.com/hassio-addons/addon-tailscale/issues/120
- https://github.com/hassio-addons/addon-tailscale/issues/96
- https://github.com/hassio-addons/addon-tailscale/issues/119
- https://github.com/hassio-addons/addon-tailscale/issues/62
- https://github.com/hassio-addons/addon-tailscale/issues/124
- https://github.com/hassio-addons/addon-tailscale/pull/89
- https://github.com/hassio-addons/addon-tailscale/pull/122

All of these issues have been marked as stale, while the maintainer has had no time to address them, while all of them are legitimate issues.

Previous version: https://github.com/hassio-addons/addon-tailscale/pull/110

@frenck **this is why i originally proposed this**, this is not a "difference of opinion", unless your 'opinion' on this is that it's better to let legitimate issues languish and auto-close than it is to let them sit there until someone addresses them. Then that is not maintenance, that's negligence.

If you don't have time to maintain this addon, please delegate it to someone else, or pause/defer maintenance by preventing this bot from reaping legitimate issues.

### CODE REVIEW

**Comment by frenck** [comment]
Won't be removing stale bot. Thanks for your suggestion though.

../Frenck

**Comment by ShadowJonathan** [comment]
@frenck then at least address the other issues, you're letting a bunch of issues rot stale while you yourself have said that you're interested in solving them, add a `no-stale` label to them then.

You're solving nothing by closing this.

If you cannot maintain this addon, find someone else to let maintain it, i'd volunteer.

**Comment by frenck** [comment]
> then at least address the other issues

I have over 600 tasks in my github inbox list, besides my personal tasks. Things take time.

> You're solving nothing by closing this.

Well... To be fair, merging this would solve anything either. If anything, this PR wasted more of my time.

> If you cannot maintain this addon, find someone else to let maintain it, i'd volunteer.

Good. Will consider it someday.

../Frenck

**Comment by ShadowJonathan** [comment]
> To be fair, merging this wouldn't solve anything either.

It would solve the problem of legitimate issues languishing in this repository, which would come up again, again and again, which wastes everyone's time involved, and potentially hides problems that people once cared about, and now not anymore, because you clearly don't care for their respect by not considering your own limits with these repositories, letting their issues rot away, without any response.

You're managing all these repos on your own, without delegation, and apparantly without a real will to want to manage them in the first place. Find someone who wants to do this job, then.

**Comment by frenck** [comment]
Please see my previous answer.

Thanks 👍 

../Frenck

**Comment by ShadowJonathan** [comment]
You clearly haven't read mine.

**Comment by frenck** [comment]
I did. Could you now stop? Thanks 👍 

../Frenck

**Comment by ShadowJonathan** [comment]
So let me just re-iterate then; you're completely fine with all the issues here in this repo being closed for being "stale", while you yourself have no time to address them all in due time (before them going stale), thereby basically nullifying any valid issue that people might come up with here?

**Comment by frenck** [comment]
See my answers above.

I asked you to stop, which you just ignore. This is now hindering progress on anything and just becoming annoying.

../Frenck

**Comment by ShadowJonathan** [comment]
I've considered your request for me to stop as much as you've considered the questions i put up

**Comment by frenck** [comment]
🤷 I asked nicely.

../Frenck

**Pull request closed without merging**
